// checksum 0xfde6 version 0x90005
/*
  This file was generated by the Qt Quick 2 Application wizard of Qt Creator.
  QtQuick2ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QTQUICK2APPLICATIONVIEWER_H
#define QTQUICK2APPLICATIONVIEWER_H

#include <qglobal.h>
#include <QObject>

#if (QT_VERSION >= QT_VERSION_CHECK(5,0,0))
#include <QtQuick/QQuickView>
#endif

class QtQuick2ApplicationViewer
#if (QT_VERSION >= QT_VERSION_CHECK(5,0,0))
                : public QQuickView
#endif
{
    Q_OBJECT
#if (QT_VERSION >= QT_VERSION_CHECK(5,0,0))
public:
    explicit QtQuick2ApplicationViewer(QWindow *parent = 0);
    virtual ~QtQuick2ApplicationViewer();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);

    void showExpanded();

private:
    class QtQuick2ApplicationViewerPrivate *d;
#endif
};

#endif // QTQUICK2APPLICATIONVIEWER_H
